server:
  port: 8088
rocketmq:
  # NameServer
  name-server: 192.168.211.132:9876
  # 默认的消息组
  consumer:
    group: ifdts-group-consumer
    topic: ifdts-topic
    tags: admittedCustomerTag

# 安装到本地仓库命令 mvn install -Dmaven.skip.test=true
# java打包命令  mvn clean package -Dmaven.test.skip=true